/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dashboard_pkge;

import Dashboard_pkge.dbconnection;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import static java.lang.System.in;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;



/**
 *
 * @author User1
 */
public class employeeregistration extends javax.swing.JFrame {

    /**
     * Creates new form employeeregistration
     */
    
    
//    Dashboard_ui dash = new Dashboard_ui();
//   
//    String namerr = dash.empname1.getText();
//    
//    
    public employeeregistration() {
        initComponents();
       
        
    }
    
    
    
    
//    public employeeregistration(String fname) {
//        initComponents();
//        nametxt.setText(fname);
//        
//    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        registerbtn = new javax.swing.JButton();
        nametextfield = new javax.swing.JTextField();
        agetextfield = new javax.swing.JTextField();
        gendertextfield = new javax.swing.JTextField();
        idnotextfield = new javax.swing.JTextField();
        phonenotextfield = new javax.swing.JTextField();
        addresstextfield = new javax.swing.JTextField();
        emailtextfield = new javax.swing.JTextField();
        educationtextfield = new javax.swing.JTextField();
        designationtextfield1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        signinbtn2 = new javax.swing.JButton();
        signinbtn3 = new javax.swing.JButton();
        signinbtn4 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        nameerr = new javax.swing.JLabel();
        nameerr1 = new javax.swing.JLabel();
        nameerr2 = new javax.swing.JLabel();
        nameerr3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/registerbtn.png"))); // NOI18N
        registerbtn.setBorderPainted(false);
        registerbtn.setContentAreaFilled(false);
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });
        jPanel1.add(registerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 930, -1, -1));

        nametextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nametextfield.setBorder(null);
        nametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametextfieldActionPerformed(evt);
            }
        });
        jPanel1.add(nametextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 176, 370, 30));

        agetextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        agetextfield.setBorder(null);
        jPanel1.add(agetextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 360, 30));

        gendertextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gendertextfield.setBorder(null);
        jPanel1.add(gendertextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 360, 30));

        idnotextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idnotextfield.setBorder(null);
        jPanel1.add(idnotextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 360, 30));

        phonenotextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phonenotextfield.setBorder(null);
        jPanel1.add(phonenotextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 630, 360, 30));

        addresstextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addresstextfield.setBorder(null);
        jPanel1.add(addresstextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 740, 360, 30));

        emailtextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailtextfield.setBorder(null);
        emailtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtextfieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailtextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 860, 360, 30));

        educationtextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        educationtextfield.setBorder(null);
        jPanel1.add(educationtextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 630, 360, 30));

        designationtextfield1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        designationtextfield1.setBorder(null);
        jPanel1.add(designationtextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 740, 360, 30));

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 1, 43)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("NEW EMPLOYEE REGISTRATION");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 850, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel9.setText("ID Number");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel10.setText("Phone Number ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel12.setText("E-mail Address");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 810, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel14.setText("Gender");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel16.setText("Age");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel18.setText("Profile Picture");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 150, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 730, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel26.setText("Education");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 580, -1, -1));

        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 180, 230, 280));

        signinbtn2.setIcon(new javax.swing.ImageIcon("G:\\huice_bar assets\\buttons\\backbtn.png")); // NOI18N
        signinbtn2.setBorderPainted(false);
        signinbtn2.setContentAreaFilled(false);
        signinbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(signinbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        signinbtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/clearbtn.png"))); // NOI18N
        signinbtn3.setBorderPainted(false);
        signinbtn3.setContentAreaFilled(false);
        signinbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(signinbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 930, -1, -1));

        signinbtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/chooseimagebtn.png"))); // NOI18N
        signinbtn4.setBorderPainted(false);
        signinbtn4.setContentAreaFilled(false);
        signinbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(signinbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 480, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 620, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 730, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel30.setText("Designation");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 690, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel31.setText("Address");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 690, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel32.setText("Name");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        nameerr.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        nameerr.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(nameerr, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, -1, -1));

        nameerr1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        nameerr1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(nameerr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 780, -1, -1));

        nameerr2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        nameerr2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(nameerr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 780, -1, -1));

        nameerr3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        nameerr3.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(nameerr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard_pkge/image size txt.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 250, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/Logingb.png"))); // NOI18N
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1460, 1100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1452, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed

    
            
           if (nametextfield.getText().isEmpty()) {  
    nameerr3.setText("User name Required");
     
} else if (idnotextfield.getText().isEmpty()) {  
    nameerr.setText("id Number Required");
    
}else if (addresstextfield.getText().isEmpty()) {  
    nameerr1.setText("Address Required");
    
}else if (designationtextfield1.getText().isEmpty()) {  
    nameerr2.setText("designation Required");
    
} else{
        JOptionPane.showMessageDialog(rootPane,"Data Send Succesfully");
       }
            
            
            
            
            
            
      
        
        
        
        
        
        try {
   
    String name1 = nametextfield.getText();
    int age = Integer.parseInt(agetextfield.getText());
    String gender =gendertextfield.getText();
    String idno = idnotextfield.getText();
    int phoneno = Integer.parseInt(phonenotextfield.getText());
    String address = addresstextfield.getText();
    String email = emailtextfield.getText();

    String education = educationtextfield.getText();
    String designation = designationtextfield1.getText();
    
  
    Connection con = dbconnection.dbconnection();
    String sql = "INSERT INTO employee (name, age, gender, idno, phoneno, address, email, photo, education, designation) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ? )";
    PreparedStatement ste = con.prepareStatement(sql);
    
   ste.setString(1, name1);         
    ste.setInt(2, age);             
    ste.setString(3, gender);       
    ste.setString(4, idno);         
    ste.setInt(5, phoneno);      
    ste.setString(6, address);     
    ste.setString(7, email);
    ste.setBytes(8, name);
    ste.setString(9, education);
    ste.setString(10, designation);
    ste.executeUpdate();

    
} catch (Exception e) {
    System.out.println(e);
}



    
    }//GEN-LAST:event_registerbtnActionPerformed

    private void educationtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_educationtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_educationtextfieldActionPerformed

    private void signinbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signinbtn2ActionPerformed

    private void signinbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signinbtn3ActionPerformed

    private void signinbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtn4ActionPerformed
       JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        
        photo.setIcon(new ImageIcon(file.toString()));
        filename = file.getAbsolutePath();

try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte [] buf = new byte [1024];
            for(int readnum;(readnum = fis.read(buf))!= -1;){
            
                bos.write(buf,0,readnum);
        } 
            name = bos.toByteArray();

            
        } catch (Exception e) {
        }

    }//GEN-LAST:event_signinbtn4ActionPerformed

    private void nametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametextfieldActionPerformed
  
    }//GEN-LAST:event_nametextfieldActionPerformed

    private void emailtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtextfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeeregistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeeregistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeeregistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeeregistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeeregistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstextfield;
    private javax.swing.JTextField agetextfield;
    private javax.swing.JLabel back;
    private javax.swing.JTextField designationtextfield1;
    private javax.swing.JTextField educationtextfield;
    private javax.swing.JTextField emailtextfield;
    private javax.swing.JTextField gendertextfield;
    private javax.swing.JTextField idnotextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameerr;
    private javax.swing.JLabel nameerr1;
    private javax.swing.JLabel nameerr2;
    private javax.swing.JLabel nameerr3;
    public javax.swing.JTextField nametextfield;
    private javax.swing.JTextField phonenotextfield;
    private javax.swing.JLabel photo;
    private javax.swing.JButton registerbtn;
    private javax.swing.JButton signinbtn2;
    private javax.swing.JButton signinbtn3;
    private javax.swing.JButton signinbtn4;
    // End of variables declaration//GEN-END:variables
byte[] name = null;
String filename = null;
}
