/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dashboard_pkge;

import Dashboard_pkge.dbconnection;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author User1
 */
public class updateemployee extends javax.swing.JFrame {

    /**
     * Creates new form updateemployee
     */
    public updateemployee() {
        initComponents();
      
    }
        public void data1(){
    int empid = Integer.parseInt(empidltextfield.getText());
       
        try {
             String sql = "Select * from employee where empid = '"+empid+"'";
            Connection con = dbconnection.dbconnection();
    
    PreparedStatement ste = con.prepareStatement(sql);
    
    
    ResultSet rs = ste.executeQuery();
//    ste.setInt(11, empid);
    if(rs.next()){
    String name1 = rs.getString(1);
    String age = rs.getString(2);
    String gender = rs.getString(3);
    String idno = rs.getString(4);
    int phoneno = rs.getInt(5);
    String address = rs.getString(6);
    String email = rs.getString(7);

    String education = rs.getString(9);
    String designation = rs.getString(10);
    
    
    InputStream in = rs.getBinaryStream(8);
    
    BufferedImage bufferedImage = ImageIO.read(in);
            ImageIcon imageIcon = new ImageIcon(bufferedImage);
            photo.setIcon(imageIcon);
    
    updatenametextfield1.setText(name1);
    updateagetextfield1.setText(String.valueOf(age));
    updategendertextfield1.setText(gender);
    updateidnotextfield1.setText(idno);
    updatephonenotextfield1.setText(String.valueOf(phoneno));
    updateaddresstextfield1.setText(address); 
    updateemailtextfield1.setText(email);       
    updateEducationtextfield1.setText(education);      
    updatedesignationtextfield2.setText(designation);     
           
    }
        } catch (Exception e) {
            
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        signinbtn1 = new javax.swing.JButton();
        updatenametextfield1 = new javax.swing.JTextField();
        updateagetextfield1 = new javax.swing.JTextField();
        updategendertextfield1 = new javax.swing.JTextField();
        updateidnotextfield1 = new javax.swing.JTextField();
        updatephonenotextfield1 = new javax.swing.JTextField();
        updateaddresstextfield1 = new javax.swing.JTextField();
        updateemailtextfield1 = new javax.swing.JTextField();
        updateEducationtextfield1 = new javax.swing.JTextField();
        updatedesignationtextfield2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        signinbtn2 = new javax.swing.JButton();
        signinbtn3 = new javax.swing.JButton();
        signinbtn4 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        empidltextfield = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signinbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/editbtnn.png"))); // NOI18N
        signinbtn1.setBorderPainted(false);
        signinbtn1.setContentAreaFilled(false);
        signinbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(signinbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 940, -1, -1));

        updatenametextfield1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updatenametextfield1.setBorder(null);
        updatenametextfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatenametextfield1ActionPerformed(evt);
            }
        });
        jPanel1.add(updatenametextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 176, 370, 30));

        updateagetextfield1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateagetextfield1.setBorder(null);
        jPanel1.add(updateagetextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 360, 30));

        updategendertextfield1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updategendertextfield1.setBorder(null);
        jPanel1.add(updategendertextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 360, 30));

        updateidnotextfield1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateidnotextfield1.setBorder(null);
        jPanel1.add(updateidnotextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 360, 30));

        updatephonenotextfield1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updatephonenotextfield1.setBorder(null);
        updatephonenotextfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatephonenotextfield1ActionPerformed(evt);
            }
        });
        jPanel1.add(updatephonenotextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 630, 360, 30));

        updateaddresstextfield1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateaddresstextfield1.setBorder(null);
        jPanel1.add(updateaddresstextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 740, 360, 30));

        updateemailtextfield1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateemailtextfield1.setBorder(null);
        updateemailtextfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateemailtextfield1ActionPerformed(evt);
            }
        });
        jPanel1.add(updateemailtextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 860, 360, 30));

        updateEducationtextfield1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateEducationtextfield1.setBorder(null);
        updateEducationtextfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEducationtextfield1ActionPerformed(evt);
            }
        });
        jPanel1.add(updateEducationtextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 630, 360, 30));

        updatedesignationtextfield2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updatedesignationtextfield2.setBorder(null);
        jPanel1.add(updatedesignationtextfield2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 740, 360, 30));

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 1, 43)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("UPADTE EMPLOYEE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 850, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel9.setText("ID Number");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel10.setText("Phone Number ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel12.setText("E-mail Address");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 810, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel14.setText("Gender");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel16.setText("Age");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel18.setText("Profile Picture");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 150, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 730, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel26.setText("Education");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 580, -1, -1));

        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 180, 230, 280));

        signinbtn2.setIcon(new javax.swing.ImageIcon("G:\\huice_bar assets\\buttons\\backbtn.png")); // NOI18N
        signinbtn2.setBorderPainted(false);
        signinbtn2.setContentAreaFilled(false);
        signinbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(signinbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        signinbtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/clearbtn.png"))); // NOI18N
        signinbtn3.setBorderPainted(false);
        signinbtn3.setContentAreaFilled(false);
        signinbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(signinbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 930, -1, -1));

        signinbtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/chooseimagebtn.png"))); // NOI18N
        signinbtn4.setBorderPainted(false);
        signinbtn4.setContentAreaFilled(false);
        signinbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(signinbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 480, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 620, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 730, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel30.setText("Designation");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 690, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel31.setText("Address");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 690, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel32.setText("Name");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        empidltextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        empidltextfield.setBorder(null);
        empidltextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empidltextfieldActionPerformed(evt);
            }
        });
        jPanel1.add(empidltextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 860, 360, 30));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/register text field.png"))); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 850, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel13.setText("EMP ID");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 810, -1, -1));

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard_pkge/searchbtn.png"))); // NOI18N
        search.setBorder(null);
        search.setBorderPainted(false);
        search.setContentAreaFilled(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 950, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/Logingb.png"))); // NOI18N
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1460, 1100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1452, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signinbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtn1ActionPerformed
    try {
        String name1 = updatenametextfield1.getText().trim();
        String ageText = updateagetextfield1.getText().trim();
        String gender = updategendertextfield1.getText().trim();
        String idNo = updateidnotextfield1.getText().trim();
        String phoneNoText = updatephonenotextfield1.getText().trim();
        String address = updateaddresstextfield1.getText().trim();
        String email = updateemailtextfield1.getText().trim();
        String education = updateEducationtextfield1.getText().trim();
        String designation = updatedesignationtextfield2.getText().trim();
        String empIdText = empidltextfield.getText().trim();

        if (empIdText.isEmpty()) {
            System.out.println("Employee ID is required to update the record.");
            return;
        }
        int test = 0;
        int empId = Integer.parseInt(empIdText);

        // Build the dynamic SQL query
        StringBuilder sql = new StringBuilder("UPDATE employee SET ");
        List<Object> parameters = new ArrayList<>();

        if (!name1.isEmpty()) {
            sql.append("name = ?, ");
            parameters.add(name1);
            test = 1;
        }
        if (!ageText.isEmpty()) {
            sql.append("age = ?, ");
            parameters.add(Integer.parseInt(ageText));
            test = 1;
        }
        if (!gender.isEmpty()) {
            sql.append("gender = ?, ");
            parameters.add(gender);
            test = 1;
        }
        if (!idNo.isEmpty()) {
            sql.append("idno = ?, ");
            parameters.add(idNo);
            test = 1;
        }
        if (!phoneNoText.isEmpty()) {
            sql.append("phoneno = ?, ");
            parameters.add(Integer.parseInt(phoneNoText));
            test = 1;
        }
        if (!address.isEmpty()) {
            sql.append("address = ?, ");
            parameters.add(address);
            test = 1;
        }
        if (!email.isEmpty()) {
            sql.append("email = ?, ");
            parameters.add(email);
            test = 1;
            
        }if (!education .isEmpty()) {
            sql.append("education  = ?, ");
            parameters.add(education );
            test = 1;
            
        }if (!designation.isEmpty()) {
            sql.append("designation = ?, ");
            parameters.add(designation);
            test = 1;
        }

        // Assuming `photoData` is set to a valid byte array for the photo field
        try {
             if(test == 1){
        
     }else{
     String sql2 = "UPDATE employee SET photo = ? where empid = ?  ";
            Connection con = dbconnection.dbconnection();
           PreparedStatement ste = con.prepareStatement(sql2);
       
           ste.setBytes(1, name);
           ste.setString(2,empIdText);
         ste.executeUpdate();
     }
        } catch (Exception e) {
        }

        // Remove the last comma and add the WHERE clause
        sql.delete(sql.length() - 2, sql.length()).append(" WHERE Empid = ?;");
        parameters.add(empId);

        // Prepare the statement
        Connection con = dbconnection.dbconnection();
        PreparedStatement ste = con.prepareStatement(sql.toString());

        // Set parameters dynamically
        for (int i = 0; i < parameters.size(); i++) {
            Object param = parameters.get(i);
            if (param instanceof Integer) {
                ste.setInt(i + 1, (Integer) param);
            } else if (param instanceof String) {
                ste.setString(i + 1, (String) param);
            } else if (param instanceof byte[]) {
                ste.setBytes(i + 1, (byte[]) param);
            }
        }
        
        

        // Execute the update
        int rowsUpdated = ste.executeUpdate();
        if (rowsUpdated > 0) {
            System.out.println("Employee updated successfully.");
        }

    } catch (NumberFormatException e) {
        System.out.println("Please enter valid numbers for age, phone number, and employee ID.");
    } catch (Exception e) {
        System.out.println(e);
    }





    }//GEN-LAST:event_signinbtn1ActionPerformed

    private void updatenametextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatenametextfield1ActionPerformed

    }//GEN-LAST:event_updatenametextfield1ActionPerformed

    private void updateemailtextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateemailtextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateemailtextfield1ActionPerformed

    private void signinbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signinbtn2ActionPerformed

    private void signinbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtn3ActionPerformed
         updatenametextfield1.setText("");
        updateagetextfield1.setText("");
        updategendertextfield1.setText("");
        updateidnotextfield1.setText("");
        updatephonenotextfield1.setText("");
         updateaddresstextfield1.setText("");
        updateemailtextfield1.setText("");
         updateEducationtextfield1.setText("");
         updatedesignationtextfield2.setText("");
         empidltextfield.setText("");       // TODO add your handling code here:
    }//GEN-LAST:event_signinbtn3ActionPerformed

    private void signinbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtn4ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();

        photo.setIcon(new ImageIcon(file.toString()));
        filename = file.getAbsolutePath();

        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte [] buf = new byte [1024];
            for(int readnum;(readnum = fis.read(buf))!= -1;){

                bos.write(buf,0,readnum);
            }
            name = bos.toByteArray();
            //            Connection con = dbconnection.dbconnection();
            //            String sql = "INSERT INTO employee (name, age, gender, idno, phoneno, address, email, photo, education, designation, empid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            //            PreparedStatement ste = con.prepareStatement(sql);
            //
            //
            //
            //
            //
            //
            //
            //         ste.executeQuery();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_signinbtn4ActionPerformed

    private void updateEducationtextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEducationtextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateEducationtextfield1ActionPerformed

    private void empidltextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empidltextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empidltextfieldActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
  data1();


        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void updatephonenotextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatephonenotextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatephonenotextfield1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateemployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JTextField empidltextfield;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JLabel photo;
    private javax.swing.JButton search;
    private javax.swing.JButton signinbtn1;
    private javax.swing.JButton signinbtn2;
    private javax.swing.JButton signinbtn3;
    private javax.swing.JButton signinbtn4;
    private javax.swing.JTextField updateEducationtextfield1;
    private javax.swing.JTextField updateaddresstextfield1;
    private javax.swing.JTextField updateagetextfield1;
    private javax.swing.JTextField updatedesignationtextfield2;
    private javax.swing.JTextField updateemailtextfield1;
    private javax.swing.JTextField updategendertextfield1;
    private javax.swing.JTextField updateidnotextfield1;
    public javax.swing.JTextField updatenametextfield1;
    private javax.swing.JTextField updatephonenotextfield1;
    // End of variables declaration//GEN-END:variables
byte[] name = null;
String filename = null;
}
