/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginpkage;

import Dashboard_pkge.Dashboard_ui;
import Dashboard_pkge.employeeregistration;
import Dashboard_pkge.updateemployee;
import javax.swing.JOptionPane;
import menue.mENURE2;



/**
 *
 * @author User1
 */
public class adminlogin extends javax.swing.JFrame {

    
    
    
    
    

    
    /**
     * Creates new form adminlogin
     */
    public adminlogin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        signinbtn1 = new javax.swing.JButton();
        signinbtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        usernamelable1 = new javax.swing.JLabel();
        pw = new javax.swing.JPasswordField();
        uname1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 15)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBox1.setText("Remember me?");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 730, 150, 40));

        signinbtn1.setIcon(new javax.swing.ImageIcon("G:\\huice_bar assets\\buttons\\backbtn.png")); // NOI18N
        signinbtn1.setBorderPainted(false);
        signinbtn1.setContentAreaFilled(false);
        signinbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(signinbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 50, -1, -1));

        signinbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/Sign_in.png"))); // NOI18N
        signinbtn.setBorderPainted(false);
        signinbtn.setContentAreaFilled(false);
        signinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtnActionPerformed(evt);
            }
        });
        jPanel1.add(signinbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 820, -1, -1));

        jLabel12.setFont(new java.awt.Font("Forte", 1, 43)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Administration Login");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("ONLY ADMIN HAVE THE PERMISSION");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 880, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Password");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, -1, -1));

        usernamelable1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        usernamelable1.setForeground(new java.awt.Color(102, 102, 102));
        usernamelable1.setText("Username");
        jPanel1.add(usernamelable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        pw.setBorder(null);
        jPanel1.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 680, 330, 30));

        uname1.setBorder(null);
        jPanel1.add(uname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 370, 30));

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Sign in to stay connected.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("G:\\huice_bar assets\\Email Input.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("G:\\huice_bar assets\\Email Input.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));

        jLabel11.setFont(new java.awt.Font("Goudy Old Style", 1, 43)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("EMPLOYEE INFORMATION");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpkage/LOGIN REGister.png"))); // NOI18N
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1460, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1452, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void signinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtnActionPerformed
      String username = uname1.getText();
        String psword = pw.getText();
        
        
       if(username.equals("Gin_Tonic_Admin")&& psword.equals("GT_Admin123")){
           
           JOptionPane.showMessageDialog(rootPane,"Welcome Admin");
       updateemployee empre = new updateemployee();
        empre.setVisible(true);
        this.dispose();;
       }
       
       else{
        JOptionPane.showMessageDialog(rootPane,"please enterd Valid user name and Password");
       }
    }//GEN-LAST:event_signinbtnActionPerformed

    private void signinbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtn1ActionPerformed
       
    }//GEN-LAST:event_signinbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pw;
    private javax.swing.JButton signinbtn;
    private javax.swing.JButton signinbtn1;
    private javax.swing.JTextField uname1;
    public javax.swing.JLabel usernamelable1;
    // End of variables declaration//GEN-END:variables
}
